Repository SesacAcademy/SesacAnimal, pull requests merged in 2023-11, with the labels that each got.

#24 Feature/view create view
  src/main/resources/static/reviewimgdummy/img1.jpg
  src/main/resources/templates/fragments/footer/footer.html
  src/main/resources/templates/fragments/header/header.html
  src/main/resources/templates/views/review/readreview.html
  src/main/resources/templates/views/review/reviewlist.html
  src/main/resources/templates/views/review/writereview.html
Labels: Feature

#30 입양 뷰 추가 사항 및 변경 PR
  src/main/java/com/project/animal/adoption/controller/AdoptionController.java
  src/main/resources/static/css/adoption.css
  src/main/resources/static/css/header.css
  src/main/resources/templates/fragments/header/header.html
  src/main/resources/templates/views/adoption/adoption.html
  src/main/resources/templates/views/adoption/adoptionList.html
  src/main/resources/templates/views/adoption/adoption_edit.html
  src/main/resources/templates/views/adoption/adoption_read.html
  src/main/resources/templates/views/adoption/adoption_write.html
Labels: Done

#46 입양 게시판 Entity/DTO 생성
  src/main/generated/com/project/animal/adoption/domain/QAdoption.java
  src/main/generated/com/project/animal/adoption/domain/QAdoptionComment.java
  src/main/generated/com/project/animal/adoption/domain/QAdoptionImage.java
  src/main/generated/com/project/animal/adoption/domain/QAdoptionLike.java
  src/main/generated/com/project/animal/adoption/domain/QTempImage.java
  src/main/java/com/project/animal/adoption/controller/AdoptionController.java
  src/main/java/com/project/animal/adoption/domain/Adoption.java
  src/main/java/com/project/animal/adoption/domain/AdoptionComment.java
  src/main/java/com/project/animal/adoption/domain/AdoptionImage.java
  src/main/java/com/project/animal/adoption/domain/AdoptionLike.java
  src/main/java/com/project/animal/adoption/domain/TempImage.java
  src/main/java/com/project/animal/adoption/dto/AdoptionReadDto.java
  src/main/java/com/project/animal/adoption/dto/AdoptionWriteDto.java
  src/main/java/com/project/animal/adoption/repository/AdoptionImageRepository.java
  src/main/java/com/project/animal/adoption/repository/AdoptionRepository.java
  src/main/java/com/project/animal/adoption/service/AdoptionImageService.java
  src/main/java/com/project/animal/adoption/service/AdoptionService.java
  src/main/java/com/project/animal/member/domain/Member.java
  src/main/resources/static/css/adoption.css
  src/main/resources/static/img/cat_basic.jpg
  src/main/resources/templates/views/adoption/adoption_edit.html
  src/main/resources/templates/views/adoption/adoption_list.html
  src/main/resources/templates/views/adoption/adoption_read.html
  src/main/resources/templates/views/adoption/adoption_write.html
Labels: Done

#44 실종 게시판 로직 (머지순서 1번)
  src/main/generated/com/project/animal/missing/domain/QMissingPost.java
  src/main/java/com/project/animal/missing/controller/MissingController.java
  src/main/java/com/project/animal/missing/domain/MissingPost.java
  src/main/java/com/project/animal/missing/dto/ListResponseDto.java
  src/main/java/com/project/animal/missing/dto/MissingListResDto.java
  src/main/java/com/project/animal/missing/dummy/MissingPostDummy.java
  src/main/java/com/project/animal/missing/dummy/sql/createMissingDummy.sql
  src/main/java/com/project/animal/missing/repository/CustomMissingPostRepository.java
  src/main/java/com/project/animal/missing/repository/CustomMissingPostRepositoryImpl.java
  src/main/java/com/project/animal/missing/repository/MissingPostRepository.java
  src/main/java/com/project/animal/missing/service/MissingPostService.java
  src/main/resources/templates/views/missing/list/missingListFilter.html
Labels: Feature

#60 review 게시판 crud 구현
  src/main/generated/com/project/animal/review/domain/QReviewImage.java
  src/main/generated/com/project/animal/review/domain/QReviewPost.java
  src/main/java/com/project/animal/Application.java
  src/main/java/com/project/animal/global/common/dto/ImageListDto.java
  src/main/java/com/project/animal/global/common/entity/BaseEntity.java
  src/main/java/com/project/animal/global/common/minioserviceprovider/ImageUploadMinio.java
  src/main/java/com/project/animal/global/common/minioserviceprovider/minioException.java
  src/main/java/com/project/animal/member/domain/Member.java
  src/main/java/com/project/animal/review/constant/EndPoint.java
  src/main/java/com/project/animal/review/constant/ViewName.java
  src/main/java/com/project/animal/review/controller/ReviewController.java
  src/main/java/com/project/animal/review/domain/ReviewImage.java
  src/main/java/com/project/animal/review/domain/ReviewPost.java
  src/main/java/com/project/animal/review/dto/CreateReviewPostDto.java
  src/main/java/com/project/animal/review/dto/ReadListGeneric.java
  src/main/java/com/project/animal/review/dto/ReadOneReviewDto.java
  src/main/java/com/project/animal/review/dto/ReviewCommentDto.java
  src/main/java/com/project/animal/review/dto/ReviewPostAllDto.java
  src/main/java/com/project/animal/review/dummy/CreateMemberWithoutSecurity.java
  src/main/java/com/project/animal/review/exception/NotFoundException.java
  src/main/java/com/project/animal/review/repository/ReviewImageRepository.java
  src/main/java/com/project/animal/review/repository/ReviewRepository.java
  src/main/java/com/project/animal/review/service/ReviewImageService.java
  src/main/java/com/project/animal/review/service/ReviewService.java
  src/main/resources/static/css/review.css
  src/main/resources/static/css/reviewlist.css
  src/main/resources/static/css/writereview.css
  src/main/resources/static/css/writeview.css
  src/main/resources/templates/views/review/readReview.html
  src/main/resources/templates/views/review/readreview.html
  src/main/resources/templates/views/review/reviewList.html
  src/main/resources/templates/views/review/reviewlist.html
  src/main/resources/templates/views/review/updateReview.html
  src/main/resources/templates/views/review/writeReview.html
  src/main/resources/templates/views/review/writereview.html
Labels: Done

#78 fix: 쿠키 (JWT 토큰) 삭제 안되는 버그 해결
  src/main/java/com/project/animal/global/common/filter/JwtExceptionFilter.java
Labels: Bug Fixed

#86 feat: 로그아웃 기능 및 회원가입 폼 추가 (닉네임)
  src/main/generated/com/project/animal/member/domain/QMember.java
  src/main/java/com/project/animal/global/common/constant/EndPoint.java
  src/main/java/com/project/animal/global/common/constant/TokenTypeValue.java
  src/main/java/com/project/animal/global/common/dto/MemberDto.java
  src/main/java/com/project/animal/global/common/provider/JwtTokenProvider.java
  src/main/java/com/project/animal/global/config/SecurityConfig.java
  src/main/java/com/project/animal/member/controller/LoginController.java
  src/main/java/com/project/animal/member/controller/MemberController.java
  src/main/java/com/project/animal/member/controller/MemberControllerAdvice.java
  src/main/java/com/project/animal/member/domain/Member.java
  src/main/java/com/project/animal/member/dto/SignupFormDto.java
  src/main/java/com/project/animal/member/exception/NestedNicknameException.java
  src/main/java/com/project/animal/member/repository/MemberRepository.java
  src/main/java/com/project/animal/member/service/LoginServiceImp.java
  src/main/java/com/project/animal/member/service/MemberServiceImp.java
  src/main/java/com/project/animal/member/service/inf/LoginService.java
  src/main/resources/static/js/member/signup.js
  src/main/resources/templates/fragments/header/header.html
  src/main/resources/templates/views/index.html
  src/main/resources/templates/views/member/login.html
  src/main/resources/templates/views/member/signup.html
Labels: Feature

#87 입양 게시판 UPDATE/DELETE 기능 추가 PR
  src/main/generated/com/project/animal/adoption/domain/QAdoption.java
  src/main/generated/com/project/animal/adoption/domain/QAdoptionComment.java
  src/main/generated/com/project/animal/adoption/domain/QAdoptionImage.java
  src/main/generated/com/project/animal/adoption/domain/QAdoptionLike.java
  src/main/generated/com/project/animal/adoption/domain/QTempImage.java
  src/main/java/com/project/animal/Application.java
  src/main/java/com/project/animal/adoption/controller/AdoptionController.java
  src/main/java/com/project/animal/adoption/domain/Adoption.java
  src/main/java/com/project/animal/adoption/domain/AdoptionComment.java
  src/main/java/com/project/animal/adoption/domain/AdoptionImage.java
  src/main/java/com/project/animal/adoption/domain/AdoptionLike.java
  src/main/java/com/project/animal/adoption/domain/TempImage.java
  src/main/java/com/project/animal/adoption/dto/AdoptionEditDto.java
  src/main/java/com/project/animal/adoption/dto/AdoptionReadDto.java
  src/main/java/com/project/animal/adoption/dto/AdoptionWriteDto.java
  src/main/java/com/project/animal/adoption/repository/AdoptionImageRepository.java
  src/main/java/com/project/animal/adoption/repository/AdoptionRepository.java
  src/main/java/com/project/animal/adoption/service/AdoptionServiceImpl.java
  src/main/java/com/project/animal/adoption/service/inf/AdoptionService.java
  src/main/java/com/project/animal/adoption/test/restTemplate.java
  src/main/java/com/project/animal/global/common/constant/EndPoint.java
  src/main/java/com/project/animal/global/common/constant/ViewName.java
  src/main/java/com/project/animal/sample/openApi/controller/OpenApiData.java
  src/main/java/com/project/animal/sample/openApi/dto/OpenApiDto.java
  src/main/resources/static/css/adoption.css
  src/main/resources/static/css/adoption/adoption_edit.css
  src/main/resources/static/css/adoption/adoption_list.css
  src/main/resources/static/css/adoption/adoption_read.css
  src/main/resources/static/css/adoption/adoption_write.css
  src/main/resources/static/js/adoption/adoption_edit_delete.js
  src/main/resources/static/js/adoption/adoption_list_search.js
  src/main/resources/templates/views/adoption/adoptionList.html
  src/main/resources/templates/views/adoption/adoption_edit.html
  src/main/resources/templates/views/adoption/adoption_list.html
  src/main/resources/templates/views/adoption/adoption_read.html
  src/main/resources/templates/views/adoption/adoption_write.html
Labels: Feature, Done

#90 카카오 로그인 기능 구현 (소셜 로그인)
  src/main/java/com/project/animal/global/common/constant/AuthType.java
  src/main/java/com/project/animal/global/common/constant/EndPoint.java
  src/main/java/com/project/animal/global/common/filter/JwtAuthenticationFilter.java
  src/main/java/com/project/animal/global/common/provider/JwtTokenProvider.java
  src/main/java/com/project/animal/global/common/provider/MailAuthCodeProvider.java
  src/main/java/com/project/animal/global/common/provider/inf/TokenProvider.java
  src/main/java/com/project/animal/member/controller/LoginController.java
  src/main/java/com/project/animal/member/controller/MemberController.java
  src/main/java/com/project/animal/member/controller/TestController.java
  src/main/java/com/project/animal/member/dto/CheckMailTokenDto.java
  src/main/java/com/project/animal/member/dto/TokenDto.java
  src/main/java/com/project/animal/member/repository/MemberRepository.java
  src/main/java/com/project/animal/member/service/LoginServiceImp.java
  src/main/java/com/project/animal/member/service/MemberServiceImp.java
  src/main/java/com/project/animal/member/service/inf/LoginService.java
  src/main/resources/static/js/member/signup.js
  src/main/resources/templates/fragments/header/header.html
  src/main/resources/templates/views/error/401.html
  src/main/resources/templates/views/error/403.html
  src/main/resources/templates/views/error/404.html
  src/main/resources/templates/views/error/4xx.html
  src/main/resources/templates/views/error/500.html
  src/main/resources/templates/views/error/5xx.html
  src/main/resources/templates/views/member/login.html
Labels: Feature

#94 입양 댓글 create PR
  src/main/generated/com/project/animal/adoption/domain/QAdoptionComment.java
  src/main/java/com/project/animal/adoption/controller/AdoptionController.java
  src/main/java/com/project/animal/adoption/domain/AdoptionComment.java
  src/main/java/com/project/animal/adoption/dto/AdoptionCommentReadDto.java
  src/main/java/com/project/animal/adoption/dto/AdoptionCommentWriteDto.java
  src/main/java/com/project/animal/adoption/repository/AdoptionCommentRepository.java
  src/main/java/com/project/animal/adoption/repository/AdoptionImageRepository.java
  src/main/java/com/project/animal/adoption/service/AdoptionCommentServiceImpl.java
  src/main/java/com/project/animal/adoption/service/AdoptionServiceImpl.java
  src/main/java/com/project/animal/global/common/constant/EndPoint.java
  src/main/resources/static/css/adoption/adoption_read.css
  src/main/resources/static/js/adoption/adoption_read_comments.js
  src/main/resources/templates/views/adoption/adoption_read.html
Labels: Feature, Done

#110 리뷰 게시판 조회수, 댓글 수 표기
  src/main/java/com/project/animal/review/constant/ViewName.java
  src/main/java/com/project/animal/review/controller/ReviewCommentController.java
  src/main/java/com/project/animal/review/controller/ReviewController.java
  src/main/java/com/project/animal/review/domain/ReviewComment.java
  src/main/java/com/project/animal/review/domain/ReviewPost.java
  src/main/java/com/project/animal/review/dto/CreateReviewPostDto.java
  src/main/java/com/project/animal/review/dto/ReviewCommentDtoCount.java
  src/main/java/com/project/animal/review/dto/ReviewCommentResponseDto.java
  src/main/java/com/project/animal/review/dto/ReviewPostAllDto.java
  src/main/java/com/project/animal/review/repository/ReviewPostCustomRepository.java
  src/main/java/com/project/animal/review/repository/ReviewRepository.java
  src/main/java/com/project/animal/review/service/ReviewCommentService.java
  src/main/java/com/project/animal/review/service/mapper/ReviewCommentRequestMapper.java
  src/main/resources/templates/views/review/readReview.html
  src/main/resources/templates/views/review/readReviewFinal.html
  src/main/resources/templates/views/review/readReviewListFinal.html
  src/main/resources/templates/views/review/updateReviewFinal.html
Labels: Done

#112 입양후기 게시판 멤버 연결
  src/main/java/com/project/animal/review/controller/ReviewCommentController.java
  src/main/java/com/project/animal/review/controller/ReviewController.java
  src/main/java/com/project/animal/review/dto/ReadOneReviewDto.java
  src/main/java/com/project/animal/review/service/ReviewCommentService.java
  src/main/java/com/project/animal/review/service/ReviewService.java
  src/main/resources/templates/views/review/readReviewFinal.html
  src/main/resources/templates/views/review/readReviewListFinal.html
  src/main/resources/templates/views/review/updateReviewFinal.html
  src/main/resources/templates/views/review/writeReview.html
Labels: Feature

#113 회원 - 마이 페이지 뷰 작업
  src/main/java/com/project/animal/global/common/constant/ViewName.java
  src/main/java/com/project/animal/global/common/controller/HomeController.java
  src/main/java/com/project/animal/member/controller/MemberControllerAdvice.java
  src/main/java/com/project/animal/member/controller/MyPageController.java
  src/main/java/com/project/animal/member/domain/Member.java
  src/main/java/com/project/animal/member/service/MemberServiceImp.java
  src/main/java/com/project/animal/member/service/MyPageServiceImp.java
  src/main/java/com/project/animal/member/service/inf/MyPageService.java
  src/main/resources/static/css/member/mypage.css
  src/main/resources/static/js/member/login.js
  src/main/resources/static/js/member/signup.js
  src/main/resources/templates/fragments/header/header.html
  src/main/resources/templates/views/member/mypage_adoptionList.html
  src/main/resources/templates/views/member/mypage_boardList.html
  src/main/resources/templates/views/member/mypage_info.html
  src/main/resources/templates/views/member/mypage_password.html
  src/main/resources/templates/views/member/mypage_wishList.html
  src/main/resources/templates/views/member/signup.html
Labels: Feature

#117 입양후기 게시판 좋아요 구현, 페이징 에러 해결
  src/main/generated/com/project/animal/review/domain/QReviewPost.java
  src/main/generated/com/project/animal/review/domain/QReviewPostLike.java
  src/main/java/com/project/animal/global/common/dto/ImageListDto.java
  src/main/java/com/project/animal/global/common/exception/MinioException.java
  src/main/java/com/project/animal/global/common/provider/MinioServiceProvider.java
  src/main/java/com/project/animal/review/constant/ViewName.java
  src/main/java/com/project/animal/review/controller/ReviewCommentController.java
  src/main/java/com/project/animal/review/controller/ReviewController.java
  src/main/java/com/project/animal/review/controller/ReviewPostLikeController.java
  src/main/java/com/project/animal/review/domain/ReviewPost.java
  src/main/java/com/project/animal/review/domain/ReviewPostLike.java
  src/main/java/com/project/animal/review/dto/ReadListGeneric.java
  src/main/java/com/project/animal/review/dto/ReadOneReviewDto.java
  src/main/java/com/project/animal/review/dto/ReviewPostAllDto.java
  src/main/java/com/project/animal/review/repository/ReviewPostCustomRepository.java
  src/main/java/com/project/animal/review/repository/ReviewPostLikeRepository.java
  src/main/java/com/project/animal/review/repository/ReviewRepository.java
  src/main/java/com/project/animal/review/service/ReviewCommentService.java
  src/main/java/com/project/animal/review/service/ReviewPostLikeService.java
  src/main/java/com/project/animal/review/service/ReviewService.java
  src/main/java/com/project/animal/review/service/mapper/ReviewCommentRequestMapper.java
  src/main/java/com/project/animal/review/service/mapper/ReviewPostLikeMapper.java
  src/main/resources/templates/views/review/readListReviewBySearch.html
  src/main/resources/templates/views/review/readReview.html
  src/main/resources/templates/views/review/readReviewFinal.html
  src/main/resources/templates/views/review/readReviewListFinal.html
  src/main/resources/templates/views/review/reviewList.html
  src/main/resources/templates/views/review/updateReview.html
  src/main/resources/templates/views/review/updateReviewFinal.html
Labels: Feature

#118 입양 게시판 좋아요 기능 추가 PR
  src/main/generated/com/project/animal/adoption/domain/QAdoption.java
  src/main/generated/com/project/animal/adoption/domain/QAdoptionPostLike.java
  src/main/java/com/project/animal/adoption/controller/AdoptionController.java
  src/main/java/com/project/animal/adoption/domain/Adoption.java
  src/main/java/com/project/animal/adoption/domain/AdoptionPostLike.java
  src/main/java/com/project/animal/adoption/repository/AdoptionPostLikeRepository.java
  src/main/java/com/project/animal/adoption/repository/AdoptionRepository.java
  src/main/java/com/project/animal/adoption/service/AdoptionServiceImpl.java
  src/main/java/com/project/animal/member/domain/Member.java
  src/main/resources/static/css/adoption/adoption_list.css
  src/main/resources/static/js/adoption/adoption_list_like.js
  src/main/resources/templates/views/adoption/adoption_list.html
  src/main/resources/templates/views/adoption/adoption_read.html
Labels: Feature, Done

#121 회원 탈퇴 및 비밀번호 변경 기능 구현
  src/main/java/com/project/animal/global/common/constant/EndPoint.java
  src/main/java/com/project/animal/global/common/constant/ViewName.java
  src/main/java/com/project/animal/member/controller/LoginController.java
  src/main/java/com/project/animal/member/controller/MemberController.java
  src/main/java/com/project/animal/member/controller/MemberControllerAdvice.java
  src/main/java/com/project/animal/member/controller/MyPageController.java
  src/main/java/com/project/animal/member/dto/ChangePasswordFormDto.java
  src/main/java/com/project/animal/member/exception/NestedPhoneException.java
  src/main/java/com/project/animal/member/exception/WrongPasswordException.java
  src/main/java/com/project/animal/member/repository/MemberRepository.java
  src/main/java/com/project/animal/member/service/LoginServiceImp.java
  src/main/java/com/project/animal/member/service/MemberServiceImp.java
  src/main/java/com/project/animal/member/service/MyPageServiceImp.java
  src/main/java/com/project/animal/member/service/inf/MyPageService.java
  src/main/resources/static/css/member/mypage.css
  src/main/resources/static/js/member/mypage_info.js
  src/main/resources/static/js/member/mypage_password.js
  src/main/resources/static/js/member/signup.js
  src/main/resources/templates/views/member/mypage_info.html
  src/main/resources/templates/views/member/mypage_password.html
Labels: Feature

#122 입양후기 게시판 좋아요순, 조회수순으로 정렬
  src/main/java/com/project/animal/review/constant/ViewName.java
  src/main/java/com/project/animal/review/controller/ReviewController.java
  src/main/java/com/project/animal/review/repository/ReviewPostCustomRepository.java
  src/main/java/com/project/animal/review/repository/ReviewRepository.java
  src/main/java/com/project/animal/review/service/ReviewService.java
  src/main/resources/templates/views/review/readReviewListByFilter.html
  src/main/resources/templates/views/review/readReviewListBySearch.html
  src/main/resources/templates/views/review/readReviewListFinal.html
Labels: Feature

#129 index 홈 입양 영역 PR
  src/main/java/com/project/animal/adoption/controller/AdoptionController.java
  src/main/java/com/project/animal/adoption/repository/AdoptionRepository.java
  src/main/java/com/project/animal/adoption/service/AdoptionServiceImpl.java
  src/main/resources/static/css/adoption/adoption_index.css
  src/main/resources/static/css/header/header.css
  src/main/resources/static/img/adoption_banner.png
  src/main/resources/static/img/cat_icon.png
  src/main/resources/static/img/dog_icon.png
  src/main/resources/static/img/findnadopt.png
  src/main/resources/static/js/adoption/adoption_index.js
  src/main/resources/templates/fragments/adoption/adoption_index.html
  src/main/resources/templates/fragments/header/header.html
  src/main/resources/templates/views/adoption/adoption_edit.html
  src/main/resources/templates/views/adoption/adoption_list.html
  src/main/resources/templates/views/adoption/adoption_read.html
  src/main/resources/templates/views/adoption/adoption_write.html
  src/main/resources/templates/views/home/index.html
Labels: Doing

#138 입양 게시판 레이아웃 수정
  src/main/java/com/project/animal/adoption/controller/AdoptionController.java
  src/main/resources/static/css/adoption/adoption_edit.css
  src/main/resources/static/css/adoption/adoption_list.css
  src/main/resources/static/css/adoption/adoption_read.css
  src/main/resources/static/css/adoption/adoption_write.css
  src/main/resources/static/js/adoption/adoption_read_comments.js
  src/main/resources/templates/views/adoption/adoption_edit.html
  src/main/resources/templates/views/adoption/adoption_list.html
  src/main/resources/templates/views/adoption/adoption_read.html
  src/main/resources/templates/views/adoption/adoption_write.html
Labels: Feature, Done

#140 Header font 고정 PR
  src/main/resources/static/css/header/header.css
Labels: Feature, Done

#142 입양 리스트 swipe기능 추가 PR
  src/main/java/com/project/animal/adoption/service/AdoptionServiceImpl.java
  src/main/resources/static/css/adoption/adoption_list.css
  src/main/resources/static/css/adoption/adoption_read.css
  src/main/resources/static/js/adoption/adoption_list_swipe.js
  src/main/resources/templates/views/adoption/adoption_edit.html
  src/main/resources/templates/views/adoption/adoption_list.html
  src/main/resources/templates/views/adoption/adoption_read.html
Labels: Feature, Done

#144 마이 페이지 - 내 게시글 기능 구현
  src/main/generated/com/project/animal/member/domain/QBoard.java
  src/main/java/com/project/animal/member/controller/MyPageController.java
  src/main/java/com/project/animal/member/domain/Board.java
  src/main/java/com/project/animal/member/repository/BoardRepository.java
  src/main/java/com/project/animal/member/service/MyPageServiceImp.java
  src/main/java/com/project/animal/member/service/inf/MyPageService.java
  src/main/resources/templates/views/member/mypage_adoptionList.html
  src/main/resources/templates/views/member/mypage_boardList.html
  src/main/resources/templates/views/member/mypage_info.html
  src/main/resources/templates/views/member/mypage_password.html
  src/main/resources/templates/views/member/mypage_wishList.html
Labels: Feature

#146 header border-bottom 제거 PR
  src/main/resources/static/css/header/header.css
Labels: Feature, Done

#150 입양 상세게시판 댓글영역 마진 추가, 강아지 아이콘 변경, index select 영역 width값 수정
  src/main/resources/static/css/adoption/adoption_read.css
  src/main/resources/static/css/home/adoption_index.css
  src/main/resources/templates/views/adoption/adoption_edit.html
  src/main/resources/templates/views/adoption/adoption_list.html
  src/main/resources/templates/views/adoption/adoption_read.html
  src/main/resources/templates/views/adoption/adoption_write.html
  src/main/resources/templates/views/home/index.html
Labels: Feature, Done

#155 Index페이지 종 검색 추가 PR
  src/main/java/com/project/animal/adoption/constant/ViewName.java
  src/main/java/com/project/animal/adoption/controller/AdoptionController.java
  src/main/java/com/project/animal/global/common/constant/EndPoint.java
  src/main/java/com/project/animal/global/common/constant/ViewName.java
  src/main/java/com/project/animal/member/controller/LoginController.java
  src/main/resources/templates/fragments/home/adoption_index.html
  src/main/resources/templates/views/adoption/adoption_edit.html
  src/main/resources/templates/views/adoption/adoption_list.html
  src/main/resources/templates/views/adoption/adoption_read.html
Labels: Feature, Done

#159 index breed null일때 에러 수정 PR
  src/main/java/com/project/animal/adoption/controller/AdoptionController.java
  src/main/java/com/project/animal/member/service/LoginServiceImp.java
  src/main/resources/templates/views/adoption/adoption_list.html
Labels: Feature, Done

#162 index select 검색기능 추가(일반, 센터) PR
  src/main/java/com/project/animal/adoption/controller/AdoptionController.java
  src/main/java/com/project/animal/adoption/domain/Adoption.java
  src/main/java/com/project/animal/adoption/dto/AdoptionIndexSearchDto.java
  src/main/java/com/project/animal/adoption/repository/AdoptionRepository.java
  src/main/java/com/project/animal/adoption/service/AdoptionServiceImpl.java
  src/main/resources/templates/fragments/home/adoption_index.html
  src/main/resources/templates/views/adoption/adoption_edit.html
  src/main/resources/templates/views/adoption/adoption_list.html
  src/main/resources/templates/views/adoption/adoption_read.html
  src/main/resources/templates/views/adoption/adoption_write.html
  src/main/resources/templates/views/home/index.html
Labels: Feature, Done

#168 입양 상세 페이지 댓글 창 간격 미세 수정 PR
  src/main/java/com/project/animal/adoption/service/AdoptionServiceImpl.java
  src/main/resources/static/css/adoption/adoption_read.css
Labels: Feature, Done

#175 footer 개발자 변경 및 깃허브링크 통일
  src/main/resources/templates/fragments/footer/footer.html
Labels: Feature, Done
